### ISSUE TITLE
error messages about unknown parser type and unknown encoder

### ISSUE THREAD

**Issue by ardarico** [song940/node-dns#15]
Hi,

when I send a request to the server using dig, as shown in the README, I get a response that seems ok, but the server prints the following messages:

node-dns > unknown parser type: undefined(41)
..
node-dns > unknown encoder undefined(41)

At the client, the response starts with: 
;; Warning: Message parser reports malformed message packet.

I think the issue is in the client's request sent by dig. Is there a way to fix it?

Thanks

**Comment by song940** [comment]
@ardarico please follow https://github.com/song940/node-dns/issues/8#issuecomment-644638981
