### ISSUE TITLE
Example for UDP+TCP servers

### ISSUE THREAD

**Issue by andris9** [song940/node-dns#17]
This is not an issue but an example for anyone who wants to use dns2 both with UDP and TCP. You can find the example application [here](https://gist.github.com/andris9/abc94332be671d7bbbc3a2f617a810db).

1. Copy both files to a folder
2. Run `npm install dns2`
3. Start the app with `node app.js` – it should start both servers
4. In another terminal window try to resolve something
  * Using UDP: `dig A example.com @127.0.0.1 -p5053`
  * Using TCP: `dig A example.com +tcp @127.0.0.1 -p5053`
  * Both requests should get the same response

**Comment by eviltik** [comment]
Not enought.

I can help with more examples by doing more functional automated tests. Waiting after #31 before PR.
