### ISSUE TITLE
How to send authoritative responses?

### ISSUE THREAD

**Issue by KenADev** [song940/node-dns#2]
Hi,

is there a way to send authoritative instead of non-authoritative responses?

**Comment by KenADev** [comment]
Found it.
Use ´´´javascript
        response.header.aa = 1; //mark response as authoritative 
´´´

**Comment by KenADev** [comment]
Found it.
Use 
```javascript
response.header.aa = 1; //mark response as authoritative 
```

**Comment by risharde** [comment]
Thanks for this @KenADev
