### ISSUE TITLE
Renaming to create stringent naming

### ISSUE THREAD

**Issue by DSorlov** [song940/node-dns#27]
As I am now endeavouring to add a number of features that I personally need and also wish to contribute back I wanted to rename some in the class DNS such as:

- Client to UDPClient
- DoT to TCPClient
- DoH to DOHClient
- Google to GoogleClient

This also aligns more closely with the server naming and allows for furthering the features and methods available. This would also involve updating examples and the actual class names inside each client. Any thoughts on this?

I have created an [example](https://github.com/DSorlov/node-dns/tree/renaming) of this based on my already open PR to show what I mean. Hope that clarifies a bit.

**Comment by DSorlov** [comment]
[PR28](https://github.com/song940/node-dns/pull/28) created

**Comment by DSorlov** [comment]
Merged.

**Comment by eviltik** [comment]
Effect side ;) 

https://github.com/song940/node-dns/issues/31
