### ISSUE TITLE
unknow encoder undefined(41)

### ISSUE THREAD

**Issue by 7c** [song940/node-dns#4]
Hi,

i have developed a small demo based on your example like seen here:

```
const udp    = require('dgram');
const dns    = require('dns2');

const Packet = dns.Packet;

let rip=null;
let localPort=53;


var server = dns.createServer(function(request, send){
  var query = request.questions[0].name;
  console.log('> request %s', query);
    var response = new Packet(request);
    response.header.qr = 1;
    response.header.ra = 1;
	console.log('a');
    response.answers.push({
        name: query,
        type: Packet.TYPE.A,
        class: Packet.CLASS.IN,
        ttl: 300,
        address: rip
    });
 console.log('b');
   send(response);
});

require('dns').resolve4('ip8s.com',(err,addr)=>{
    if (err) {
        console.log(err.stack);
        process.exit(1);
    }
    rip=addr.shift();
    console.log('Will respond '+rip);
    server.listen(localPort,()=>{
        console.log("Server has been started at port *:"+localPort);
    });
});

```
I do run 9.2.1 on mac pro, everything seems to work fine. But i do get

`node-dns > unknow encoder undefined(41)
node-dns > unknow parser type: undefined(41)`

on node 4/6/8. I have not tried node9 on that ubuntu 16 machine. Is that just a requirement issue or some other problem on my side please?

**Comment by song940** [comment]
@taskinosman Everything is ok when I run your code in my macOS .
unknow encoder/decoder 41 is `EDNS`, but `EDNS` not implement for current version (see #3 )

**Comment by taskinosman** [comment]
Thanks for answer, it works on my MacPRO. It does not work proplery on ubuntu 16, with node 4/6/8/9. I am getting this error. Actually i GET a reply to resolver  BUT it also throws this error which confuses me. I dont think i am doing any extra efford for EDNS since i am using regular host command

**Comment by ptorrent** [comment]
Hello there,

Same problem here, is there a way to fix it ?

Thanks for your support !

**Comment by song940** [comment]
same as https://github.com/song940/node-dns/issues/8
