### ISSUE TITLE
When a name is not found how can a status of NXDOMAIN be returned to indicate this?

### ISSUE THREAD

**Issue by asampal** [song940/node-dns#43]
It's not clear how a status of NXDOMAIN should be returned (see https://serverfault.com/questions/373629/what-is-the-correct-response-for-a-dns-server-when-a-domain-does-not-exist).
 
Is this not possible in the current implementation?

**Comment by DerelictDrone** [comment]
Hopefully I'm not too late, but I just tested, you can edit any and all headers of a response before sending it.

So before you send(response), you just need to set response.header.rcode to either 3 or 0x03(both are treated as 3 by javascript it seems) and DiG/DNS queries will report NXDOMAIN.

Any server-side logic on determining when to send/what to do when receiving an NXDOMAIN is up to you though.

[Here's a good resource on all of the headers and their options for a DNS response](http://www.tcpipguide.com/free/t_DNSMessageHeaderandQuestionSectionFormat.htm)

**Comment by asampal** [comment]
Thanks for the info
