### ISSUE TITLE
Requester's IP

### ISSUE THREAD

**Issue by MincoMK** [song940/node-dns#60]
I want to log each requests in db. But I want to log requester's IP. `rinfo.address` returns 192.168.0.1 (It's local ip of my ipTIME router)

**Comment by Kapsonfire-DE** [comment]
ofc - the server cant get information from your iptime router which acts as proxy.

**Comment by MincoMK** [comment]
> ofc - the server cant get information from your iptime router which acts as proxy.

so how to log ip?

**Comment by Kapsonfire-DE** [comment]
you have no option for it except in a http context where you can add additionall headers- you have to log in your proxy

**Comment by risharde** [comment]
Yes I am also facing this issue and I cannot seem to come up with a solution for this :(

**Comment by risharde** [comment]
Following up on this, this all depends on how NAT is set up on your router. I'm not a NAT expert but I was able to do this by stopping all my proxy software which was forwarding DNS queries from public internet IP to my virtual machine. I'm not exactly sure why you are encountering this issue but I suspect MAYBE the router you are using is not implementing NAT properly (???). Maybe try another brand router if you have the resources to do so. @MincoMK
