### ISSUE TITLE
UDP Server Type should be configurable (udp4 or udp6)

### ISSUE THREAD

**Issue by louislam** [song940/node-dns#65]
udp4 is currently hardcoded in the `udp.js`. It cannot be accessed udp via IPv6 address.

https://github.com/song940/node-dns/blob/b2e994c0a61ad58902486ed4e9055965cf0bcb5d/server/udp.js#L9-L11

**Comment by song940** [comment]
@louislam It can be assign by `options.type` https://github.com/song940/node-dns/blob/b2e994c0a61ad58902486ed4e9055965cf0bcb5d/server/udp.js#L9-L15

**Comment by louislam** [comment]
Was overlooking it, thanks 👍

**Comment by song940** [comment]
@louislam Uptime Kuma is a great project, I love it so much 👍
