### ISSUE TITLE
malformed ipv6

### ISSUE THREAD

**Issue by Kikobeats** [song940/node-dns#70]
Using `dns2` is converting resolving `naprapatlandslaget.se` wrongly into `2a03:b0c0:3:d0:::13c1:f001`

<img width="1151" alt="CleanShot 2022-07-20 at 16 48 01@2x" src="https://user-images.githubusercontent.com/2096101/180012272-7d85d716-b93d-49ee-a27b-1c97fdbe7225.png">

Where actually the real value should be `2a03:b0c0:3:d0::13c1:f001`

**Comment by Kikobeats** [comment]
@song940 can you release a new patch version? 🙏

**Comment by song940** [comment]
+ dns2@2.0.4
