### ISSUE TITLE
Wrong response formatting for type AAAA

### ISSUE THREAD

**Issue by strivelabs-pablorb** [song940/node-dns#78]
According to the source code and documentation in order to return a valid AAAA response I have to do the following code:

```
const response = Packet.createResponseFromRequest(request);
response.answers.push({
        name: 'google.com',
        type: Packet.TYPE.AAAA,
        class: Packet.CLASS.IN,
        ttl: 10,
        address: '2a00:1450:4003:803::200e',
});
```
but currently, dig returns an error like this 
```
WARNING: Message has 12 extra bytes at end
```

**Comment by strivelabs-pablorb** [comment]
Seems to be related to this issue. https://github.com/song940/node-dns/issues/54

**Comment by strivelabs-pablorb** [comment]
Fixed. But I see that my change breaks the node 10 build @song940 shall I fix it or mark the version as a breaking change?

**Comment by song940** [comment]
@strivelabs-pablorb Yes, I already bump version to `dns2@2.1.0`.

**Comment by strivelabs-pablorb** [comment]
> @strivelabs-pablorb Yes, I already bump version to `dns2@2.1.0`.

thx and sorry because I totally forgot to manage the versioning If that is done then Ill not change the code then. Thx for the lib. 😄
